import '../globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import Menu from "@/components/Menu";
import Footer from "@/components/Footer";
import {Analytics} from '@vercel/analytics/react';

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
    viewport: "width=device-width, initial-scale=1.0, viewport-fit=cover",
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={inter.className + ""}>
                <header>
                    <Menu/>
                </header>
                {children}
                <Footer/>
                <Analytics/>
            </body>
        </html>
    )
}
